.TH CRON-QUERY 1 "September 2025" "cron-query 1.0.0" "User Commands"
.SH NAME
cron-query \- query cron schedules using natural language
.SH SYNOPSIS
.B cron-query
[\fIOPTIONS\fR] "\fIQUERY\fR"
.SH DESCRIPTION
.B cron-query
allows you to query crontab schedules using natural language phrases.
It supports querying both user and system crontabs, with various output formats.
.SH OPTIONS
.TP
.BR \-\-format " " \fIFORMAT\fR
Output format (list, table, json, csv, yaml). Default: list
.TP
.BR \-\-source " " \fISOURCE\fR
Crontab source (user, system, all). Default: user
.TP
.BR \-\-file " " \fIPATH\fR
Path to crontab file to analyze
.TP
.BR \-v ", " \-\-verbose
Enable verbose output
.TP
.BR \-\-no\-color
Disable colored output
.TP
.BR \-\-template " " \fITEMPLATE\fR
Custom output template or predefined template name
.TP
.BR \-\-list\-templates
List available predefined templates
.TP
.BR \-\-template\-help
Show template help with available variables
.TP
.BR \-\-page\-size " " \fISIZE\fR
Number of results per page (default: 20)
.TP
.BR \-\-page " " \fINUM\fR
Page number to display (default: 1)
.TP
.BR \-\-no\-pager
Disable pagination
.SH EXAMPLES
.TP
Basic day query:
.B cron-query "jobs on Saturday"
.TP
Time-based query:
.B cron-query "jobs at 8 AM"
.TP
Relative date query:
.B cron-query "jobs this Saturday"
.TP
Time range query:
.B cron-query "jobs between 9 AM and 5 PM"
.TP
Combined query:
.B cron-query "jobs on weekdays between 9 AM and 5 PM"
.TP
JSON output:
.B cron-query --format json "jobs on Saturday"
.TP
System crontabs:
.B cron-query --source system "jobs on weekdays"
.SH FILES
.TP
.I ~/.config/cron-query/config.yaml
Optional configuration file
.TP
.I /etc/crontab
System crontab file
.TP
.I /etc/cron.d/
System crontab directory
.SH SEE ALSO
.BR crontab (5),
.BR cron (8)
.SH BUGS
Report bugs at https://github.com/yourusername/cron-query/issues
.SH AUTHOR
Anthony Baldarelli <tony.baldarelli@gmail.com>
